"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Document(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PAGE_CONTENT_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    page_content: builtins.str
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        page_content: builtins.str = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "page_content", b"page_content"]) -> None: ...

global___Document = Document

@typing.final
class RerankRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    DOCUMENTS_FIELD_NUMBER: builtins.int
    query: builtins.str
    @property
    def documents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Document]: ...
    def __init__(
        self,
        *,
        query: builtins.str = ...,
        documents: collections.abc.Iterable[global___Document] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["documents", b"documents", "query", b"query"]) -> None: ...

global___RerankRequest = RerankRequest

@typing.final
class RerankResultItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCORE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    score: builtins.float
    index: builtins.int
    def __init__(
        self,
        *,
        score: builtins.float = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["index", b"index", "score", b"score"]) -> None: ...

global___RerankResultItem = RerankResultItem

@typing.final
class RerankResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RerankResultItem]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[global___RerankResultItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results"]) -> None: ...

global___RerankResponse = RerankResponse
