# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reranker.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'reranker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereranker.proto\x12\x08reranker\"\x85\x01\n\x08\x44ocument\x12\x14\n\x0cpage_content\x18\x01 \x01(\t\x12\x32\n\x08metadata\x18\x02 \x03(\x0b\x32 .reranker.Document.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"E\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12%\n\tdocuments\x18\x02 \x03(\x0b\x32\x12.reranker.Document\"0\n\x10RerankResultItem\x12\r\n\x05score\x18\x01 \x01(\x02\x12\r\n\x05index\x18\x02 \x01(\x05\"=\n\x0eRerankResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.reranker.RerankResultItem2N\n\x0fRerankerService\x12;\n\x06Rerank\x12\x17.reranker.RerankRequest\x1a\x18.reranker.RerankResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reranker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DOCUMENT']._serialized_start=29
  _globals['_DOCUMENT']._serialized_end=162
  _globals['_DOCUMENT_METADATAENTRY']._serialized_start=115
  _globals['_DOCUMENT_METADATAENTRY']._serialized_end=162
  _globals['_RERANKREQUEST']._serialized_start=164
  _globals['_RERANKREQUEST']._serialized_end=233
  _globals['_RERANKRESULTITEM']._serialized_start=235
  _globals['_RERANKRESULTITEM']._serialized_end=283
  _globals['_RERANKRESPONSE']._serialized_start=285
  _globals['_RERANKRESPONSE']._serialized_end=346
  _globals['_RERANKERSERVICE']._serialized_start=348
  _globals['_RERANKERSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
